### ISSUE TITLE
!nostalgia crashes on new channels

### ISSUE THREAD

**Issue by Tymewalk** [Tymewalk/EfficientEnigma#10]
```Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "bot.py", line 55, in on_message
    await command_table[command](message, client)
  File "/home/tymewalk/EfficientEnigma/modules/nostalgia.py", line 15, in nostalgia
    randomtime = datetime.utcfromtimestamp(random.randint(calendar.timegm(message.channel.created_at.timetuple()), calendar.timegm(datetime.now().timetuple())))
  File "/usr/lib/python3.5/random.py", line 218, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python3.5/random.py", line 196, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (1508013726,1507995759, -17967)
```

This happened when using `!nostalgia` on a channel that had just recently been made.

**Comment by Tymewalk** [comment]
The best I can think is timezone is messing it up - I'll have to see if I can get it running solely on GMT.
